global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "p3f-backend"
    static_configs:
      - targets: ["backend:8000"]
    metrics_path: /metrics
    scrape_interval: 30s
